name: innercityallstars
favicon: null
layout_spectrum: 0.19848
typography_spectrum: 0.41585
title: brass.jazz.funk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#2c2d31'
    - '#ffffff'
    - '#926351'
    - '#a9b9c1'
  brandStrength: 0.11129054659977555
  lightness: 0.34134775470010936
  saturation: 0.75
  rhythmicContrast: 0.2907505624461919
purpose: []
